# Generated by Django 4.1.5 on 2023-02-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='item',
            new_name='title',
        ),
    ]
