# Generated by Django 4.1.5 on 2023-02-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_bid_price_remove_listing_bids_bid_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_price', to='auctions.bid'),
        ),
    ]
